language: c
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ../new_method
  - mkdir build
  - cd build
  - cmake ..
  - cd ../..
script: 
  - make -f build/Makefile
  - make -f new_method/build/Makefile

